footprint: [[-0.325, -0.175], [-0.325, 0.175], [0.325, 0.175], [0.325, -0.175]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.50
footprint_padding: 0.015
oscillation_timeout: 10.0
oscillation_distance: 0.5
#recovery_behavior_enabled: false
