positions:
  D4: 
    dir: W
    grip_dir: left
  S1:  #Down Right
    dir: E
    grip_dir: right
    x: 1.36
    y: -1.06
    front_offset: 0.1
  S2: #Down Left
    dir: W
    grip_dir: left
    x: 1.69
    y: 2.182
    front_offset: 0.1
  S5: #Up right
    dir: E
    grip_dir: left
    x: 4.85
    y: -0.94
    front_offset: 0.1
  S6: #Upcenter
    dir: E
    grip_dir: left
    x: 4.85
    y: -0.39
    front_offset: 0.93
  S7: #Up Left
    dir: E
    grip_dir: left
    x: 4.85
    y: 0.46
    front_offset: 1.75
  D3: #Conveyerbelt
    dir: S
    grip_dir: left
    x: 3.08
    y: -0.353
  S4: #Center Up
    dir: W
    grip_dir: left
    x: 3.76
    y: 0.87
      
  S3: #Center Down
    dir: E
    grip_dir: left
    x: 1.61
    y: 0.93
 
  D0:
    dir: S
    x: 0
    y: 0

  D1: #between centerDown  and Belt
    x: 1.52
    y: 0.10

  D2: #between down right and Bild
    x: 2.07
    y: -0.75


