gripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: gripper_joint
    joint_speed: 2.0
    motor_master:
        id: 1
        init: 512
        min: 0
        max: 1024
    motor_slave:
        id: 2
        calbration_offset: 0
