locations:
  - {name: T11, dir: N, sleep: 3, type: BNT}
  - {name: T11, dir: E, sleep: 3, type: BNT}
  - {name: T11, dir: S, sleep: 3, type: BNT}
  - {name: T11, dir: W, sleep: 3, type: BNT}
  - {name: T12, dir: N, sleep: 3, type: BNT}
  - {name: T12, dir: E, sleep: 3, type: BNT}
  - {name: T12, dir: S, sleep: 3, type: BNT}
  - {name: T12, dir: W, sleep: 3, type: BNT}
  - {name: T13, dir: N, sleep: 3, type: BNT}
  - {name: T13, dir: E, sleep: 3, type: BNT}
  - {name: T13, dir: S, sleep: 3, type: BNT}
  - {name: T13, dir: W, sleep: 3, type: BNT}
  - {name: S11, dir: N, sleep: 3, type: BNT}
  - {name: S11, dir: E, sleep: 3, type: BNT}
  - {name: S11, dir: S, sleep: 3, type: BNT}
  - {name: S11, dir: W, sleep: 3, type: BNT}
  - {name: S12, dir: N, sleep: 3, type: BNT}
  - {name: S12, dir: E, sleep: 3, type: BNT}
  - {name: S12, dir: S, sleep: 3, type: BNT}
  - {name: S12, dir: W, sleep: 3, type: BNT}
  - {name: S13, dir: N, sleep: 3, type: BNT}
  - {name: S13, dir: E, sleep: 3, type: BNT}
  - {name: S13, dir: S, sleep: 3, type: BNT}
  - {name: S13, dir: W, sleep: 3, type: BNT}
  - {name: S14, dir: N, sleep: 3, type: BNT}
  - {name: S14, dir: E, sleep: 3, type: BNT}
  - {name: S14, dir: S, sleep: 3, type: BNT}
  - {name: S14, dir: W, sleep: 3, type: BNT}
  - {name: S15, dir: N, sleep: 3, type: BNT}
  - {name: S15, dir: E, sleep: 3, type: BNT}
  - {name: S15, dir: S, sleep: 3, type: BNT}
  - {name: S15, dir: W, sleep: 3, type: BNT}
  - {name: S16, dir: N, sleep: 3, type: BNT}
  - {name: S16, dir: E, sleep: 3, type: BNT}
  - {name: S16, dir: S, sleep: 3, type: BNT}
  - {name: S16, dir: W, sleep: 3, type: BNT}
  - {name: S17, dir: N, sleep: 3, type: BNT}
  - {name: S17, dir: E, sleep: 3, type: BNT}
  - {name: S17, dir: S, sleep: 3, type: BNT}
  - {name: S17, dir: W, sleep: 3, type: BNT}
